# Form implementation generated from reading ui file 'ScannerApp/UI_Files/ConfirmUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


'''
THIS SOFTWARE, ITS SOURCE CODE, AND ANY DISTRIBUTIONS THEREOF IS PROPERTY OF GEORGE MASON UNIVERSITY.
AUTHOR : MARTIN HAYNESWORTH
'''

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogConfirm(object):
    def setupUi(self, DialogConfirm):
        DialogConfirm.setObjectName("DialogConfirm")
        DialogConfirm.resize(194, 148)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogConfirm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=DialogConfirm)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(DialogConfirm)
        self.buttonBox.accepted.connect(DialogConfirm.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogConfirm.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogConfirm)

    def retranslateUi(self, DialogConfirm):
        _translate = QtCore.QCoreApplication.translate
        DialogConfirm.setWindowTitle(_translate("DialogConfirm", "Confirm"))
        self.label.setText(_translate("DialogConfirm", "Label"))
