# Form implementation generated from reading ui file 'UI_Files/OkUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogOk(object):
    def setupUi(self, DialogOk):
        DialogOk.setObjectName("DialogOk")
        DialogOk.resize(209, 126)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        DialogOk.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogOk)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=DialogOk)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=DialogOk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(DialogOk)
        QtCore.QMetaObject.connectSlotsByName(DialogOk)

    def retranslateUi(self, DialogOk):
        _translate = QtCore.QCoreApplication.translate
        DialogOk.setWindowTitle(_translate("DialogOk", "Dialog"))
        self.label.setText(_translate("DialogOk", "TextLabel"))
        self.pushButton.setText(_translate("DialogOk", "Ok"))
