# Form implementation generated from reading ui file 'UI_Files/OptionsUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogOptions(object):
    def setupUi(self, DialogOptions):
        DialogOptions.setObjectName("DialogOptions")
        DialogOptions.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(12)
        DialogOptions.setFont(font)
        DialogOptions.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(DialogOptions)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=DialogOptions)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.button_box = QtWidgets.QGroupBox(parent=DialogOptions)
        self.button_box.setTitle("")
        self.button_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.button_box.setObjectName("button_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.button_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.option_btn = QtWidgets.QPushButton(parent=self.button_box)
        self.option_btn.setObjectName("option_btn")
        self.verticalLayout.addWidget(self.option_btn)
        self.back_btn = QtWidgets.QPushButton(parent=self.button_box)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout.addWidget(self.back_btn)
        self.gridLayout.addWidget(self.button_box, 1, 0, 1, 1)

        self.retranslateUi(DialogOptions)
        QtCore.QMetaObject.connectSlotsByName(DialogOptions)

    def retranslateUi(self, DialogOptions):
        _translate = QtCore.QCoreApplication.translate
        DialogOptions.setWindowTitle(_translate("DialogOptions", "Dialog"))
        self.label.setText(_translate("DialogOptions", "TextLabel"))
        self.option_btn.setText(_translate("DialogOptions", "Option 1"))
        self.back_btn.setText(_translate("DialogOptions", "Back"))
